import Link from "next/link";

import { LedgerPanel, LedgerRow, LedgerRows } from "@/components/app/ledger";
import { Badge } from "@/components/ui/badge";
import type { RankedFinishPublicPool } from "@/lib/ranked-finish/persistence";

export function RankedFinishPublicPanels({ pool, participantNoun }: { pool: RankedFinishPublicPool; participantNoun: string }) {
  const leader = pool.latestStandings[0];
  const totalPositions = pool.settings.markets.reduce((total, market) => total + market.positions, 0);
  const enteredPositions = Object.values(pool.settings.results).reduce((count, positions) => count + positions.length, 0);
  return <><LedgerPanel><LedgerRows className="grid md:grid-cols-4 md:divide-x md:divide-y-0"><LedgerRow><p className="text-xs font-medium uppercase text-muted-foreground">Entries</p><p className="mt-2 text-3xl font-semibold text-brand-ink">{pool.entries.length}</p></LedgerRow><LedgerRow><p className="text-xs font-medium uppercase text-muted-foreground">Leader</p><p className="mt-2 text-2xl font-semibold text-brand-ink">{leader?.entryName ?? "TBD"}</p><p className="text-sm text-muted-foreground">{leader ? `${leader.total} points` : "Awaiting results"}</p></LedgerRow><LedgerRow><p className="text-xs font-medium uppercase text-muted-foreground">Results entered</p><p className="mt-2 text-3xl font-semibold text-brand-ink">{enteredPositions}/{totalPositions}</p></LedgerRow><LedgerRow><p className="text-xs font-medium uppercase text-muted-foreground">Event</p><p className="mt-2 text-xl font-semibold text-brand-ink">{pool.settings.basics.eventLabel}</p></LedgerRow></LedgerRows></LedgerPanel><section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem] xl:items-start"><LedgerPanel title="Result board" description="Finishing positions are recorded in order."><LedgerRows>{pool.settings.markets.flatMap((market) => Array.from({ length: market.positions }, (_, index) => { const competitor = pool.settings.competitors.find((candidate) => candidate.id === pool.settings.results[market.id]?.[index]); return <LedgerRow key={`${market.id}-${index + 1}`} className="flex items-center justify-between gap-4"><div><p className="font-semibold text-brand-ink">{market.label} P{index + 1}</p><p className="text-sm text-muted-foreground">{competitor?.name ?? "Pending"}</p></div><Badge variant={competitor ? "secondary" : "outline"}>{competitor ? "Recorded" : "Pending"}</Badge></LedgerRow>; }))}</LedgerRows></LedgerPanel><RankedFinishLeaderboard pool={pool} participantNoun={participantNoun} preview /></section></>;
}

export function RankedFinishLeaderboard({ pool, participantNoun, preview = false }: { pool: RankedFinishPublicPool; participantNoun: string; preview?: boolean }) {
  const hasStandings = pool.latestStandings.length > 0;
  const standings = pool.latestStandings.slice(0, preview ? 5 : undefined);
  const entries = pool.entries.slice(0, preview ? 5 : undefined);
  const hasMoreRows = (hasStandings ? pool.latestStandings.length : pool.entries.length) > (hasStandings ? standings.length : entries.length);
  return <LedgerPanel title="Leaderboard" description="Standings update whenever a finishing position is recorded."><LedgerRows>{hasStandings ? standings.map((row) => <LedgerRow key={row.entryId} className="flex items-center justify-between gap-4"><div><p className="font-semibold text-brand-ink">{row.rank}. {row.entryName}</p><p className="text-sm text-muted-foreground">Max {row.maxPoints} points</p></div><p className="text-xl font-bold text-brand-ink">{row.total}</p></LedgerRow>) : entries.map((entry) => <LedgerRow key={entry.entryId}><p className="font-semibold text-brand-ink">{entry.entryName}</p><p className="text-sm text-muted-foreground">Submitted predictions awaiting results.</p></LedgerRow>)}{!pool.entries.length ? <LedgerRow><p className="text-sm text-muted-foreground">No submitted {participantNoun} predictions yet.</p></LedgerRow> : null}</LedgerRows>{preview && hasMoreRows ? <div className="border-t px-5 py-4"><Link href={`/pools/${pool.poolSlug}/leaderboard`} className="text-sm font-semibold text-brand-ink hover:text-brand-hot">View full standings</Link></div> : null}</LedgerPanel>;
}
